### ISSUE TITLE
ESEF validation changes according to the ESEF reporting manual 2022

### ISSUE THREAD

**Issue by sachakaelin** [Arelle/Arelle#350]
### What should we change and why?

Dear Arelle team,

ESMA released a new 2022 reporting manual at the end of August 2022 (https://www.esma.europa.eu/file/24176/download?token=1z_i7DCc). There are many changes, but at least some of them don't have any technical implications for the processor (or the ESEF validation plugin).

Please find an overview here, which I hope will help you to focus on the technical aspects of the validation. Of course feel free to let me know about any disagreement with my valuation. Also, unfortunately I was not able to verify all of the below rules and some may need some discussion.

- **Guidance 1.0.1 [new]** – _no implications for technical valdation_
- **Guidance 1.0.2 [new]** – _no implications for technical valdation_
- **Guidance 1.1.2 [updated]** – _no implications for technical valdation_
- **Guidance 1.3.3 [updated]** – _no implications for technical valdation_
- **Guidance 1.6.1 [updated]** – I assume the severty level should be decreased from error to warning and the message should be changed "[ESEF.RTS.Annex.IV.Par.4.2.monetaryConceptWithoutBalance] Extension monetary concepts **SHOULD** provide balance attribute:"
- **Guidance 1.9.1 [new]** – _no implications for technical valdation_
- **Guidance 1.9.2 [new]** – _no implications for technical valdation_
- **Guidance 1.9.3 [new]** – _no implications for technical valdation_
- **Guidance 2.2.4 [updated]** – I am unsure if this needs adaption of the technical validation.
- **Guidance 2.2.5 [new]** – _no implications for technical valdation_
- **Guidance 2.2.6 [new]** – Concepts of type nonnum:textBlockItemType MUST be escaped when its content contains a `<` (U+003C) and/or `&` (U+0026) character (I am unsure if there are no additional "invalid" characters in XML, but ESMA clearly only states these two)
- **Guidance 2.5.1 [updated]** – Check for [ESEF.2.5.1.executableCodePresent] must be extended to check against "mailto" links. As far as I can see Arelle does not yet check for these.
- **Guidance 3.2.1 [removed]** – Remove check for [ESEF.3.2.1.extensionTaxonomyElementNameDoesNotFollowLc3Convention]
- **Guidance 3.2.5 [removed]** – Remove check for [ESEF.3.2.5.abstractConceptDefinitionInExtensionTaxonomy]. Unfortunately, I cannot say for sure if this check exists, as our software does not yet allow to create extension abstract concepts
- **Guidance 3.3.1 [updated]** – As with the above, unfortunately I cannot check if there is validation rule already, but Arelle should raise a warning if a concept is anchored to an abstract concept
- **Guidance 3.4.5 [updated]** – I think "ESMA RTS on ESEF" validation must raise an error if standard labels of the ESEF taxonomy are duplicated in the extension taxonomy. E.g. "[ESEF.RTS.Annex.IV.Par.8] Extension taxonomies shall not override or replace standard labels"
- **Guidance 3.4.6 [updated]** – I think I remember there are checks for 3.4.6 in the ESMA RTS on ESEF validation, but I am not sure if these or some of them need to be changed fom severety level error to warning based on this new guidance?
- **Guidance 4.1.1 [updated]** – As far as I can see "ESMA RTS on ESEF Uncosolidated" does not disallow XHTML within ZIP files in the first hand, so probably no changes necessary.
- **Guidance 4.1.3 [updated]** – _no implications for technical valdation_

Please let me know if there are any questions.

Thanks!

**Comment by austinmatherne-wk** [comment]
Hi @sachakaelin. Thank you for the analysis. It's appreciated.

The folks at Acsone are working on the ESEF 2022 validation updates. Their work is available on a [feature branch of their fork](https://github.com/acsone/Arelle/tree/feature/ESEF_2022). We had a call today where we discussed how we want to integrate their work into the master branch of Arelle. They're going to move their ESEF 2022 work into a new plugin (so the 2021 and 2022 validations can coexist) and open a PR here with the validation updates they've completed so far.

Once that's merged we'll begin tracking the renaming validation updates in GitHub issues here and work to combine the two plugins (ESEF 2021 and 2022) into a single plugin with a flag to control which year's rules are run.

**Comment by sachakaelin** [comment]
@austinmatherne-wk Thank you for your swift reply. I see the folks at Acsone adressed (at least) most of the topics mentioned above. I am looking forward for their (and your) implementation and would be happy to assist with any testing necessary.

**Comment by austinmatherne-wk** [comment]
Hi @sachakaelin,

We've released the 2022 validation updates as a separate [`ESEF_2022` plugin](https://github.com/Arelle/Arelle/tree/master/arelle/plugin/validate/ESEF_2022). There will probably be some minor changes (the ESEF 2022 conformance suite hasn't been released yet for us to confirm compliance), but it should be largely stable at this point if you'd like to do some testing.

**Comment by sachakaelin** [comment]
@austinmatherne-wk Thank you, good news. I had a look at it, using Arelle 2.1.3 (on AMD64) and the new plugin.

Some thoughts:

- Guidance 1.6.1 [updated] is still very strict ("MUST"). I assume you discussed this and probably there is a disparity in the RTS vs. reporting manual (Manual 2022 is no longer as strict and to me points more to "SHOULD")?
- Guidance 3.4.5 [updated]: In my opinion, this test always throws an incorrect warning message. E.g. using test G3-4-5_1 (TC1_valid.zip) from Conformance Suite 2021 results in [ESEF.3.4.5.missingLabelForRoleInReportLanguage] Label for standard role SHOULD be available in report language for concepts: esef_cor:NotesAccountingPoliciesAndMandatoryTags. - http://www.esma.europa.eu/taxonomy/2021-03-24/esef_cor.xsd 163

However, I think this standard label is correctly available in esef-cor-lab-{{lang}}.xml. I also checked packages in different languages and the warning seems to affect every package I tried.
- Guidance 3.4.5 [updated]: I might be wrong, but I think additional standard labels in an extension taxonomy (which "replace") standard labels of the core taxonomy should throw a warning (or error), but this seems to be accepted by the new plugin. 

> Moreover, according to paragraph 8 of Annex IV of the RTS on ESEF, issuers shall not override or replace standard labels (i.e. labels defined in the standard label role) of core taxonomy elements. This means that in cases where the standard labels of the core taxonomy are used, no standard label for such core taxonomy element should be presented in an issuer’s extension taxonomy label linkbase (standard labels for core taxonomy elements are referenced from the ESEF core taxonomy label linkbase files).

In my opinion this would mean that my fictitious presentation linkbase with 

`    <link:loc xlink:type="locator" xlink:href="http://xbrl.ifrs.org/taxonomy/2021-03-24/full_ifrs/full_ifrs-cor_2021-03-24.xsd#ifrs-full_DeferredTaxAssets" xlink:label="ifrs-full_DeferredTaxAssets" />
    <link:label id="label_ifrs-full_DeferredTaxAssets" xlink:type="resource" xlink:role="http://www.xbrl.org/2003/role/label" xlink:label="label_ifrs-full_DeferredTaxAssets" xml:lang="de">Das ist ein Test</link:label>
    <link:labelArc xlink:type="arc" xlink:arcrole="http://www.xbrl.org/2003/arcrole/concept-label" xlink:from="ifrs-full_DeferredTaxAssets" xlink:to="label_ifrs-full_DeferredTaxAssets" priority="10" />`

should raise at least a warning?

![grafik](https://user-images.githubusercontent.com/17023528/201878198-f881d0f8-0c7a-48d3-8865-bce8f95f3919.png)

The other new and/or updated checks did not raise any questions with me (but I might not have tested all of them).

**Comment by gmongelli** [comment]
Hi everybody,

Regarding the first comment on Guidance 3.4.5, we shall address that issue as soon as the ESEF 2022 conformance suite is out thank you to @sachakaelin for signalling it.
 
Regarding the second comment on Guidance 3.4.5, we are preparing at Acsone a new pull request implementing the change.

As a matter of fact, the RTS states clearly in Annex IV, paragraph 8 that overriding a standard label is forbidden.

Best reagards,

Greg

**Comment by sachakaelin** [comment]
Hi @derekgengenbacher-wf and @gmongelli , thank you both. We had a discussion yesterday, and whlie the RTS clearly talks about standard labels, the Reporting Manual could probably be understood to also aks the same for other label roles (when they are present in the core taxonomy)?
>The above recommendation should not prevent issuers from defining issuer-specific labels for core taxonomy elements to better align with the human readable layer, providing that they are defined in ‘xlink:role’ **other than already defined labels in the ESEF core taxonom**y (e.g. verboseLabel)

**Comment by gmongelli** [comment]
Hi,
I am not sure of having understood the question.
In the ESEF manuel, they give e recommendation on how to customise the labels "legally":

1. Define a new label with a label role that is not yet used by the IFRS or ESEF taxonomies. They give the example of the role 'http://www.xbrl.org/2003/role/verboseLabel'.
2. In the presentation linkbase, use the attribute `preferredLabel` to specify the role to be used ('http://www.xbrl.org/2003/role/verboseLabel' in the example).

This makes it possible to customise labels without overriding any standard label defined in the core taxonomies! If for instance the core taxonomy defines 'http://www.xbrl.org/2003/role/label' and 'http://www.xbrl.org/2003/role/terseLabel', these must not be overridden (for a given language). On the other side, if 'http://www.xbrl.org/2003/role/verboseLabel' is not used in the core taxonomies, custom labels of that role may be defined! All these examples make use of 'standard' labels...

Is that what you question was about, @sachakaelin?

Greg

**Comment by derekgengenbacher-wf** [comment]
This is our [PR](https://github.com/Arelle/Arelle/pull/511) to update the validations.

**Comment by sachakaelin** [comment]
@gmongelli I agree you can use (e.g.) the verbose label role, which is shown as an example. But my understanding of this particular guidance is that you should also not overwrite @preferredLabel (e.g. http://www.xbrl.org/2003/role/totalLabel or http://www.xbrl.org/2003/role/periodEndLabel) if it exists in the core taxonomy... I hope this claryfies a bit what I meant?

Sacha

**Comment by gmongelli** [comment]
Hi Sacha,

Again, from the RTS, Annex IV, paragraph 8, it concludes with:

_"Issuer specific labels may be added to the core taxonomy _elements."_

The only legal way to implement that is to apply the "preferredLabel" attribute in the presentation linkbase and use label roles not yet used in the core taxonomy.

I would suggest to wait for the publishing of the ESEF 2022 conformance suite (expected before the end of the year 2022).

Perhaps it will contain some samples that will show us what to do.

Greg

**Comment by sachakaelin** [comment]
Hi Greg,
I agree with you. But is my understand wrong, that a presentation link like 
` <link:loc xlink:type="locator" xlink:href="http://xbrl.ifrs.org/taxonomy/2021-03-24/full_ifrs/full_ifrs-cor_2021-03-24.xsd#ifrs-full_DeferredTaxAssets" xlink:label="ifrs-full_DeferredTaxAssets" /> <link:label id="label_ifrs-full_DeferredTaxAssets" xlink:type="resource" xlink:role="http://www.xbrl.org/2003/role/label" xlink:label="label_ifrs-full_DeferredTaxAssets" xml:lang="de">Das ist ein Test</link:label> <link:labelArc xlink:type="arc" xlink:arcrole="http://www.xbrl.org/2003/arcrole/concept-label" xlink:from="ifrs-full_DeferredTaxAssets" xlink:to="label_ifrs-full_DeferredTaxAssets" priority="10" />`
shoud throw an error or warning from the plugin, because the same label is available in the core taxonomy?

Thanks,
Sacha

**Comment by sachakaelin** [comment]
Hi Greg,
> The only legal way to implement that is to apply the "preferredLabel" attribute in the presentation linkbase and use label roles not yet used in the core taxonomy.

I think we have the same understanding and I agree the 2022 conformane suite will (hopfully) help.
Let me check the latest plugin when it is released. I was unsure if it will only check for overwritten standard labels (and not applied preferred labels, which are availble in the core taxonomy too).

Sacha

**Comment by sachakaelin** [comment]
Hi both.

Sorry to bother you once again. In Arelle 2.30 I still see:
`[ESEF.3.4.5.missingLabelForRoleInReportLanguage] Label for standard role SHOULD be available in report language for concepts: esef_cor:NotesAccountingPoliciesAndMandatoryTags. - http://www.esma.europa.eu/taxonomy/2021-03-24/esef_cor.xsd 163`

It seems to only affect reports in English, when I create a German report it's not there (anymore).
However, I think the label linkbase of the core taxonomy includes the English version as well?
- `esef_taxonomy_2021\www.esma.europa.eu\taxonomy\2021-03-24\esef_cor-lab-en.xml` > line 19
- `esef_taxonomy_2021\www.esma.europa.eu\taxonomy\2021-03-24\esef_cor-lab-de.xml` > line 20542

Do I get anything wrong regarding this?

All other issues seem to have been adressed (or need to be looked at, when the conformance suite 22 is realeased) 👍 .

Thanks,
Sacha

**Comment by gmongelli** [comment]
HI @sachakaelin ,

I do not experience any spurious `ESEF.3.4.5.missingLabelForRoleInReportLanguage` errors.

Could it be that the taxonomy extension is missing the English language? The warning would for instance be generated if you give an English XHTML file and you provide a German-only taxonomy extension.

Best regards,

Greg

**Comment by sachakaelin** [comment]
Thanks @gmongelli 

I can also reproduce this with `esef_conformance_suite_2021\esef_conformance_suite_2021\tests\inline_xbrl\G2-1-2\TC1_valid.zip`:

`[ESEF.3.4.5.missingLabelForRoleInReportLanguage] Label for standard role SHOULD be available in report language for concepts: esef_cor:NotesAccountingPoliciesAndMandatoryTags. - http://www.esma.europa.eu/taxonomy/2021-03-24/esef_cor.xsd 163
[info:profileActivity] validating ESMA RTS on ESEF-2022 filing rules 0.093 secs
 - abc-2019-12-31.xhtml 
validated in 1.52 secs`

**Comment by gmongelli** [comment]
You are right, @sachakaelin , it still happens in the master branch of Arelle.
We'll take a look at it when the new conformance suite will be out.

**Comment by sachakaelin** [comment]
Appreciate it, Greg! Happy holidays 🙂

**Comment by sachakaelin** [comment]
Hi Greg, 

the new conformance suite is out: https://www.esma.europa.eu/sites/default/files/library/esef_conformance_suite_2022.zip.
A quick try with the latest version of Arelle and test `\G2-1-2\TC1_valid.zip` (conformance suite 2022, ESEF Taxonomy 2022) seems this issue does **not** persist.

However, I wonder if this points to an issue in the ESEF 2021 taxonomy rather than the new ESEF-2022 plugin (or both in combination)?

**Comment by gmongelli** [comment]
Hi @sachakaelin ,

You are right, the issue has gone away in Arelle 2.3.3, but I do not think it was an ESEF 2021 taxonomy issue.

As a matter of fact, both the 2021 and 2022 versions of the G2-1-2 no longer generate the issue.

This makes me think that the issue has been corrected in Arelle.

Best regards,

Greg

**Comment by sachakaelin** [comment]
Hi @gmongelli ,

unfortunately I am not able to confirm this. I can still see the issue in the 2021 version (with Arelle 2.3.3), while it is not there in version 2022:
```
loaded in 2.29 secs
views 1.41 secs
[ESEF.2.5.1.executableCodePresent] Inline XBRL documents MUST NOT contain executable code: script - abc-2019-12-31.xhtml 
[ESEF.2.5.1.executableCodePresent] Inline XBRL documents MUST NOT contain executable code: script - abc-2019-12-31.xhtml 
[info:profileActivity] validating ESMA RTS on ESEF-2022 filing rules 0.076 secs
 - abc-2019-12-31.xhtml 
validated in 1.68 secs
loaded in 2.37 secs
views 1.30 secs
[ESEF.2.5.1.executableCodePresent] Inline XBRL documents MUST NOT contain executable code: script - abc-2019-12-31.xhtml 
[ESEF.2.5.1.executableCodePresent] Inline XBRL documents MUST NOT contain executable code: script - abc-2019-12-31.xhtml 
[ESEF.3.4.5.missingLabelForRoleInReportLanguage] Label for standard role SHOULD be available in report language for concepts: esef_cor:NotesAccountingPoliciesAndMandatoryTags. - http://www.esma.europa.eu/taxonomy/2021-03-24/esef_cor.xsd 163
[info:profileActivity] validating ESMA RTS on ESEF-2022 filing rules 0.084 secs
 - abc-2019-12-31.xhtml 
validated in 1.71 secs
```

Best regards,
Sacha

**Comment by gmongelli** [comment]
Hi @sachakaelin ,

I have used the following command line:

```
arelleCmdLine.py --plugins validate/ESEF --formula run --disclosureSystem esef -v --file test_suites/ESEF/2021/tests/inline_xbrl/G2-1-2/TC1_valid.zip
```
What is yours?

Best regards,

Greg

**Comment by sachakaelin** [comment]
Hi @gmongelli ,

So far I only used the GUI version for my local testing. 

Out of interest: Is the argument for the new plugin still `--plugins validate/ESEF`? My assumption was it will become `--plugins validate/ESEF_2022`?

Best regards,
Sacha

**Comment by gmongelli** [comment]
Hi,

Thank you, I shall test that as soon as possible.

You are right, for any new validation, you must use `--plugins validate/ESEF_2022`.  In my specific scenario, I tested the ESEF 2021 rules with the ESMA 2021 conformance test suite.

Best regards,

Greg

**Comment by sachakaelin** [comment]
Hi @gmongelli 

Thank you once again. I just updated my comment above as I can see the same result on CLI than in the GUI.

Best,
Sacha

**Comment by sachakaelin** [comment]
Hi @gmongelli 

Disabling the iXBL viewer results in no warning or errors using the Conformance Suite 2022.
```
loaded in 19.23 secs
views 2.21 secs
[info:profileActivity] validating ESMA RTS on ESEF-2022 filing rules 0.091 secs
 - abc-2019-12-31.xhtml 
Formula xpath2 grammar initialized in 0.39 secs
validated in 2.07 secs
```

However, Conformance Suite 2021 `\G2-1-2\TC1_valid.zip` still shows the warning for 3.4.5.:
```
loaded in 7.43 secs
views 1.46 secs
[ESEF.3.4.5.missingLabelForRoleInReportLanguage] Label for standard role SHOULD be available in report language for concepts: esef_cor:NotesAccountingPoliciesAndMandatoryTags. - http://www.esma.europa.eu/taxonomy/2021-03-24/esef_cor.xsd 163
[info:profileActivity] validating ESMA RTS on ESEF-2022 filing rules 0.079 secs
 - abc-2019-12-31.xhtml 
validated in 1.53 secs
```
Best reagrds,
Sacha

**Comment by austinmatherne-wk** [comment]
Hi @sachakaelin,

I don't get the `ESEF.3.4.5` error using the 2021 conformance suite with the 2021 plugin (`validate/ESEF`) or when using the 2022 conformance suite with the 2022 plugin (`validate/ESEF_2022`).

Are you perhaps using the 2022 plugin with the 2021 conformance suite?

**Comment by sachakaelin** [comment]
Hi @austinmatherne-wk,

yes, when I tested the 2022 plugin in the first place, the conformance suite 2022 (and ESEF Taxonomy 2022) were not yet released, so I had to use `\G2-1-2\TC1_valid.zip` from the conformance suite 2021 with taxonomy 2021 (as nothing newer was available).

While I understand this warning does not show up anymore usig the conformance suite 2022 (and ESEF Taxonomy 2022), I still don't see why it should happen using the `\G2-1-2\TC1_valid.zip` package and the ESEF Taxonomy 2021. I still think it's false positive (only affecting english reports), but I might be wrong.

**Comment by sachakaelin** [comment]
Ok, thanks for clarifying. 

But that means filings using the ESEF Taxonomy 2021 will cannot be checked against the guidance of the ESEF reporting manual 2022, which was released in august last year?

I understand its not a legally binding document, but I am unsure if this is 100% correct.

Never mind, the taxonomy 2022 can be used as of now, so I assume we can close this issue? Shall I do that?

**Comment by austinmatherne-wk** [comment]
Yes, I think we can close this. If you run into any other issues please report them.

**Comment by sachakaelin** [comment]
Will sure do :-).  Appreciate your help with this @gmongelli @austinmatherne-wk
